--
platform: linux
image: docker:///maven#3.3.3

inputs:
  - name: sample-git
  - name: ci-git

run:
  path: ci-git/mvn-task/mvn-exe.sh
  args: ["sample-git", "package", "true"]

outputs:
  - name: pkg-out
    path: sample-git/target
