---
platform: linux
image: docker:///maven#3.3.3

params:
  POM_PATH:

inputs:
  - name: source-git
  - name: reserved-job-git

outputs:
  - name: pkg-out

run:
  path: reserved-job-git/java-mvn/mvn-exe.sh
  args: ["tbd", "package", "true"]

#outputs:
#  - name: pkg-out
#    path: source-git/src/PaasXpertPortal/target
